### ISSUE TITLE
error: failed to run custom build command for `openssl v0.9.24`                                                              

### ISSUE THREAD

**Issue by streaps** [Johni0702/mumble-web-proxy#1]
I get a build error on Ubuntu 18.10. I tried with both libssl1.0-dev (1.0.2n) and libssl-dev (1.1.1). Any idea how I can fix it, I never build any rust sources before. rustc 1.30.0, cargo 0.31.0.

```
# cargo build --release
[...]
   Compiling openssl-sys v0.9.39                                                                                             
   Compiling openssl v0.10.15   
   Compiling openssl v0.9.24                                                                                                 
error: failed to run custom build command for `openssl v0.9.24`                                                              
process didn't exit successfully: `/root/repos/mumble-web-proxy/target/release/build/openssl-08d84935427db742/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: build_script_build::main
   7: std::rt::lang_start::{{closure}}
   8: std::panicking::try::do_call
   9: __rust_maybe_catch_panic
  10: std::rt::lang_start_internal
  11: main
  12: __libc_start_main
  13: _start
```

**Comment by Johni0702** [comment]
I updated `native-tls` and `tokio-tls` to `0.2` which should get rid of the `openssl:0.9` dependency in favor of `0.10` in the hope that it builds for you (and requiring both versions was a bit pointless anyway).

**Comment by streaps** [comment]
Now I'm stuck here:

```
   Compiling tokio-tls v0.2.0                                                                                                
error: failed to run custom build command for `mumble-web-proxy v0.1.0 (/root/repos/mumble-web-proxy)`                       
process didn't exit successfully: `/root/repos/mumble-web-proxy/target/release/build/mumble-web-proxy-64384a7483bb1d0b/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'protoc: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: build_script_build::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
  12: __rust_maybe_catch_panic
  13: std::rt::lang_start_internal
  14: main
  15: __libc_start_main
  16: _start
```

**Comment by Johni0702** [comment]
My bad, looks like I forgot to add a particular (empty) directory to git while still assuming it to exist in the build script. It should be building now (just tried it in a mostly fresh Fedora 28 VM).

**Comment by streaps** [comment]
It compiled succesfully :). Praise Rust for not eating all the RAM of my tiny server.
